# Проксі для API
[[redirects]]
  from = "/api/*"
  to = "http://3.218.8.20/:splat"
  status = 200
  force = true

# SPA fallback для всіх інших маршрутів
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
