[[redirects]]
  from = "/api/*"
  to = "https://obminbook.us-east-1.elasticbeanstalk.com/:splat"
  status = 200
  force = true

# SPA fallback - всі неіснуючі шляхи перенаправляємо на index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200